## k8s集群版部署

## 命名空间

apiVersion: v1
kind: Namespace
metadata:
  name: k8s-boot-ns

---
## 部署

apiVersion: apps/v1
kind: Deployment #部署
metadata:
  name: k8s-boot-dep
  namespace: k8s-boot-ns
  labels:
    app: k8s-devops-boot
spec:
  replicas: 1 #1个副本
  selector:
    matchLabels:
      app: k8s-devops-boot
  template:
    metadata:
      namespace: k8s-boot-ns
      labels:
        app: k8s-devops-boot
    spec:
      containers:
      - name: k8s-devops-boot
        image: registry.cn-hangzhou.aliyuncs.com/he_tree_terr/k8s-devops-boot:0.0.2-SNAPSHOT #刚刚push到阿里云上的镜像地址
        ports:
        - containerPort: 8080 #默认springboot端口
        env:
        - name: PROFILE
            value: dev
        - name: JAVA_OPTS
            value: -Xms128m -Xmx128m -Xss1024k -XX:MetaspaceSize=64m -XX:+PrintGCDetails
        - name: HTTP_URL
            value: http://k8s-boot-svc.k8s-boot-ns:8080/index?param=网络验证
---
## 服务

apiVersion: v1
kind: Service
metadata:
  name: k8s-boot-svc
  namespace: k8s-boot-ns
spec:
  selector:
    app: k8s-devops-boot #选中上面的 Deployment
  ports:
  - port: 8088 #对外8088端口
    protocol: TCP
    targetPort: 8080
  type: NodePort
  #type: ClusterIP

---
##Ingress

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  labels:
    name: nginx-ingress
spec:
  IngressClass: nginx
  rules:
  - host: k8s.boot.com #所有的host这个域名请求 转发到上面的 Service= k8s-boot-svc
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: k8s-boot-svc # 转发到 这个Service
            port:
              number: 8088
